### ISSUE TITLE
Bad output with associative arrays where value type is a struct

### ISSUE THREAD

**Issue by Herringway** [BlackEdder/painlessjson#44]
``` D
struct Test {
        struct Inner {
            string str;
        }
        Inner[string] testKey;
    }
    writeln(Test(["test": Test.Inner("Test2")]).toJSON().toPrettyString());
```

Produces the incorrect JSON output

``` json
{
    "testKey": {
        "\"test\"": {
            "str": "Test2"
        }
    }
}
```

rather than the correct output 

``` json
{
    "testKey": {
        "test": {
            "str": "Test2"
        }
    }
}
```

In addition, attempting to deserialize both the incorrect and correct output results in something even more unexpected: the entries in the associative array are missing entirely (`Test([])`)

**Comment by BlackEdder** [comment]
Thanksbfor reporting this. Haven't had a chance to look at this yet. Will hopefully get to it next week.

**Comment by Zalastax** [comment]
I've started working on this in https://github.com/Zalastax/painlessjson/tree/AAstruct
Handling AAs were not tested much at all so there are errors even in as simple things as `string[string]`

**Comment by BlackEdder** [comment]
Thanks to @Zalastax this should be fixed now. Let us know if you have any further issues.

**Comment by Herringway** [comment]
Unfortunately, the problem isn't quite solved. I've included a test that should cover the problem a little more.

``` D
struct Test {
    struct Inner {
        string str;
    }
    string[string] testKey;
    Inner[string] testKey2;
}
auto testStruct = Test(["test": "Test2"], ["test3": Test.Inner("test4")]);
assert(testStruct.toJSON()["testKey"]["test"].str == "test2", "Failed writing string[string]");
assert(testStruct.toJSON()["testKey2"]["test3"]["str"].str() == "test4", "Failed writing Test.Inner[string]");
auto deserialized = testStruct.toJSON().fromJSON!Test;
assert(("test" in deserialized.testKey) && (deserialized.testKey["test"] == "Test2"), "Failed reading string[string]");
assert(("test3" in deserialized.testKey2) && (deserialized.testKey2["test3"] == Test.Inner("test4")), "Failed reading Test.Inner[string]");
```

**Comment by Zalastax** [comment]
I'll take a look

**Comment by Zalastax** [comment]
Thanks again @Herringway for reporting and especially for adding the test cases!

**Comment by BlackEdder** [comment]
@Herringway Hopefully it is fully fixed now. Please let us know if you find any further issues.

**Comment by Herringway** [comment]
I really appreciate the work done so far, but it looks like the last test case I wrote still fails (also I realized that I mistyped a string in one of the other tests, my bad) so I'm afraid it's not quite complete yet...

**Comment by Zalastax** [comment]
@Herringway What happens if you move the type definition out from the unittest block? I managed to get this working:  

``` D
struct Test {
    struct Inner {
        string str;
    }
    string[string] testKey;
    Inner[string] testKey2;
}

unittest {
    auto testStruct = Test(["test": "Test2"], ["test3": Test.Inner("test4")]);
    assert(testStruct.toJSON()["testKey"]["test"].str == "Test2", "Failed writing string[string]");
    assert(testStruct.toJSON()["testKey2"]["test3"]["str"].str() == "test4", "Failed writing Test.Inner[string]");
    auto deserialized = testStruct.toJSON().fromJSON!Test;
    assertEqual(deserialized, testStruct);
}
```

**Comment by Herringway** [comment]
Hmm... it works. That's pretty weird. compiler bug?

**Comment by Zalastax** [comment]
I'm not sure what the compiler specifies should be accessible from templates so it might or might not be a compiler bug. Specify your classes/structs outside functions when they need to be serialized and painlessjson should be able to find them completely.

If you know that you will need subclasses I would recomend you to use https://github.com/rcorre/jsonizer for the moment and press us to take a stab at that issue.
